repos:
- hooks:
  - id: check-added-large-files
  - args:
    - --branch
    - master
    id: no-commit-to-branch
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.1.0
- hooks:
  - id: seed-isort-config
  repo: https://github.com/asottile/seed-isort-config
  rev: v2.1.0
- hooks:
  - additional_dependencies:
    - toml
    id: isort
  repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.21
- hooks:
  - id: black
    language_version: python3
  repo: https://github.com/ambv/black
  rev: 19.10b0
- hooks:
  - id: flake8
  repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.9
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.17.12
