repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    -   id: check-added-large-files
    -   id: no-commit-to-branch
        args: [--branch, master]
-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.1.0
    hooks:
    -   id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
        additional_dependencies: ['toml']
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
      language_version: python3
-   repo:  https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -    id: flake8
      #         additional_dependencies: ['flake8-docstrings', 'darglint']
