---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
  - repo: https://github.com/jazzband/pip-tools
    rev: 6.2.0
    hooks:
      - id: pip-compile
        name: pip-compile setup.cfg
        files: ^(setup\.cfg|requirements\.txt)$
        additional_dependencies: [cython] #pyrle requires cython to read setup.py
      - id: pip-compile
        name: pip-compile dev
        args: [--extra=dev, --output-file=requirements/dev.txt]
        files: ^(setup\.cfg)$
        additional_dependencies: [cython] #pyrle requires cython to read setup.py
      - id: pip-compile
        name: pip-compile test
        args: [--extra=testing, --output-file=requirements/testing.txt]
        files: ^(setup\.cfg)$
        additional_dependencies: [cython] #pyrle requires cython to read setup.py
  - repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
      - id: black
        args: [--target-version=py37]
  - repo: https://github.com/PyCQA/isort
    rev: 5.9.1
    hooks:
      - id: isort
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.20.0
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-pytest-style
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.2
    hooks:
      - id: prettier
        stages: [commit]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.17.12
    hooks:
      - id: commitizen
        stages:
          - commit-msg
