name: poreC
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - python>=3.6
  - snakemake
  - coreutils
  - pairtools
  - pairix
  - tabix
  - intake
  - intake-parquet
  - streamz
  - pyarrow
  - ncls
  - cooler
  - tqdm
  - pysam
  - biopython
  - click
  - numpy
  - pandas
  - pytest
  - pip
  - pylama
  - pylint
  - black
  - sphinx
  - sphinx-autodoc-typehints
