name: poreC
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - python>=3.6
  - snakemake
  - pairtools
  - pairix
  - tabix
  - intake
  - intake-parquet
  - streamz
  - pyarrow
  - ncls
  - tqdm
  - pysam
  - biopython
  - click
  - numpy
  - scipy
  - matplotlib
  - pytest
  - bwa
  - intervaltree
  - dataclasses
  - bedtools==2.27.1
  - pybedtools
  - pip
  - pylama
  - pylint
  - black
  - sphinx
  - sphinx-autodoc-typehints
  - pip:
    - sklearn
