name: poreC
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - snakemake
  - python>=3.6
  - pysam
  - biopython
  - click
  - numpy
  - scipy
  - matplotlib
  - pytest
  - bwa
  - intervaltree
  - dataclasses
  - pybedtools
  - pip:
    - click-log
    - sklearn