[build-system]
requires = [
    "setuptools >= 40.0.4",
    "setuptools_scm >= 2.0.0, <4",
    "wheel >= 0.29.0",
]
build-backend = 'setuptools.build_meta'

[tool.poetry]
name = "pore_c"
version = "0.3.0-rc.1"
description = "Tools to process data from an ONT poreC run"
license = "MPL 2.0"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
    "Operating System :: Unix",
    "Operating System :: POSIX",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Utilities"
    ]
authors = ["Eoghan Harrington <Eoghan.Harrington@nanoporetech.com>", "Matthew Pendleton <Matthew.Pendleton@nanoporetech.com>"]


[tool.dephell.main]
versioning = "zerover"

[tool.isort]
line-length = 120
known_third_party = ["click", "cooler", "dask", "intake", "networkx", "numpy", "pandas", "pyarrow", "pydantic", "pyranges", "pysam", "pytest", "streamz", "tqdm", "yaml"]
multi_line_output= 3
force_grid_wrap= 0
use_parentheses= true
lines_after_imports = 2
combine_as_imports = true
include_trailing_comma = true

[tool.flake8]
ignore = [ "E203"]
max-line-length = 120

[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | build
  | dist
)/
'''
