# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path


readme = ""
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, "README.rst")
if os.path.exists(readme_path):
    with open(readme_path, "rb") as stream:
        readme = stream.read().decode("utf8")


setup(
    long_description=readme,
    name="pore_c",
    version="0.3.0",
    description="Tools to process data from an ONT poreC run",
    project_urls={"repository": "https://github.com/nanoporetech/pore-c"},
    author="Eoghan Harrington",
    author_email="Eoghan.Harrington@nanoporetech.com",
    maintainer="Matthew Pendleton",
    maintainer_email="Matthew.Pendleton@nanoporetech.com",
    license="MPL 2.0",
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
        "Operating System :: Unix",
        "Operating System :: POSIX",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: Implementation :: CPython",
        "Topic :: Utilities",
    ],
    packages=["pore_c", "pore_c.analyses"],
    package_dir={"": "."},
    entry_points={"console_scripts": ["pore_c=pore_c.cli:cli"],},
    package_data={},
    install_requires=[
        "biopython==1.77",
        "click==7.0.*,>=7.0.0",
        "cooler==0.8.*,>=0.8.5",
        "cython>=0.29",
        "dask==2.*,>=2.0.0",
        "distributed==2.*,>=2.9.3",
        "intake",
        "intake-parquet",
        "ncls",
        "networkx==2.*,>=2.4.0",
        "numpy>=1.16.1",
        "pairtools",
        "pandas>=1.0.5",
        "pyarrow==1.*,>=1.0.0",
        "pydantic==1.6.1",
        "pyranges==0.0.71",
        "pysam",
        "streamz==0.*,>=0.5.2",
        "tqdm",
    ],
)
